apimServiceName: adventhealth-apim
products:
  - name: unlimited
    properties:
      displayName: Unlimited Production
      description: Unlimited Access to this API In Production
      state: published
      subscriptionRequired: "true"
